#!/bin/sh

# work around display glitches
export QT_AUTO_SCREEN_SCALE_FACTOR=1

# Set Wallpaper
if [ ! -f "$XDG_CACHE_HOME"/wallpaper.jpg ]
then
  convert "$XDG_CONFIG_HOME"/wallpaper.svg \
    -resize "$(xrandr|grep '*'|awk '{print $1}')<" \
    -quality 100 \
    "$XDG_CACHE_HOME"/wallpaper.jpg
fi
feh --no-fehbg --bg-fill "$XDG_CACHE_HOME"/wallpaper.jpg

# use GNOME Keyring
export $(gnome-keyring-daemon -s)
