set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_CROSSCOMPILING_EMULATOR wine)

set(CMAKE_C_COMPILER       i686-w64-mingw32-cc)
set(CMAKE_CXX_COMPILER     i686-w64-mingw32-c++)
set(CMAKE_Fortran_COMPILER i686-w64-mingw32-gfortran)
set(CMAKE_RC_COMPILER      i686-w64-mingw32-windres)

set(CMAKE_FIND_ROOT_PATH "/usr/i686-w64-mingw32")
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_LIBRARY_SUFFIXES .a)

set(CMAKE_C_FLAGS_INIT "-D_WIN32_WINNT=0x501 -DNTDDI_VERSION=0x05010000")
set(CMAKE_CXX_FLAGS_INIT "-D_WIN32_WINNT=0x501 -DNTDDI_VERSION=0x05010000")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static -static-libgcc -static-libstdc++")
