#!/usr/bin/fish

set acpi (acpi -b | perl -nle 'print "$1\n$2" if m{Battery 0: (\w+), (\d+)%}')
set percent $acpi[2]

if [ $percent -lt 10 ]
  echo "<span foreground=\"#ca1243\"></span>"
else if [ $percent -lt 20 ]
  echo 
else if [ $percent -lt 40 ]
  echo 
else if [ $percent -lt 60 ]
  echo 
else if [ $percent -lt 80 ]
  echo 
end
