# custom colors
colorscheme base16

# disable clippy
set global ui_options ncurses_assistant=none

# language server
eval %sh{ kak-lsp --kakoune -s $kak_session }
lsp-auto-hover-enable

hook global WinCreate .* %{
  add-highlighter window/ number-lines -hlcursor -separator ' '
  add-highlighter window/ show-matching
  add-highlighter window/ show-whitespaces -spc ' '
  search-highlighting-enable
  volatile-highlighting-enable
  auto-pairs-enable
  snippets-enable
}
