verbosity = 2

[editor]
# set to false to disable auto-hover
hover = true
# set to true to allow autocompletion with no prefix
zero_char_completion = false

[server]
# exit if no requests during given period
timeout = 1800 # seconds = 30 min

[language.rust]
extensions = ["rs"]
roots = ["Cargo.toml"]
command = "rls"

[language.javascript]
extensions = ["js", "jsx"]
roots = ["package.json"]
command = "flow-language-server"
args = ["--stdio"]

[language.json]
extensions = ["json"]
roots = ["package.json"]
command = "json-languageserver"
args = ["--stdio"]

[language.css]
extensions = ["css"]
roots = ["package.json"]
command = "css-languageserver"
args = ["--stdio"]

[language.html]
extensions = ["html"]
roots = ["package.json"]
command = "html-languageserver"
args = ["--stdio"]

[language.ocaml]
extensions = ["ml", "mli"]
roots = ["Makefile", "opam", "*.opam"]
command = "ocaml-language-server"
args = ["--stdio"]

[language.reason]
extensions = ["re", "rei"]
roots = ["package.json", "Makefile", ".git", ".hg"]
command = "ocaml-language-server"
args = ["--stdio"]

[language.python]
extensions = ["py"]
roots = ["requirements.txt", "setup.py", ".git", ".hg"]
command = "pyls"

[language.c_cpp]
extensions = ["c", "h", "cc", "hh", "cpp", "hpp", "cxx", "hxx"]
roots = ["compile_commands.json", ".git"]
command = "clangd"

[language.haskell]
extensions = ["hs"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "hie"
args = ["--lsp"]

[language.go]
extensions = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "go-langserver"
args = ["-mode", "stdio", "-gocodecompletion"]
